### ISSUE TITLE
Where to put GCP - Credentials

### ISSUE THREAD

**Issue by SimonKling** [0x4D31/galah#17]
Sorry for making a issue about it, but i really have problems setting up the vertex API. Where do I have to put the credentials ?

**Comment by 0x4D31** [comment]
Looks like you figured it out, but just in case:
You need to authenticate using the gcloud CLI (https://cloud.google.com/vertex-ai/docs/authentication#gcloud), then set the cloud project ID and cloud location in the Galah args.

**Comment by SimonKling** [comment]
Thanks for the response, yeah bc i run it with docker I had to copy the google credentials inside my docker directory and then reference it with -e GOOGLE_API_CREDENTIALS=.
