### ISSUE TITLE
application is not using the provided URL

### ISSUE THREAD

**Issue by avi7611** [0x4D31/galah#18]
when i use the parameter -u to provied my open AI server it just does't seem to use that and sends the reqeust to openAI servers. which results in invalid API key.

**Comment by 0x4D31** [comment]
When using OpenAI as the provider, the URL is ignored, and requests are sent directly to OpenAI's servers. Only when using Ollama as the provider can you set a custom URL. I assume you're using OpenAI Enterprise, which I hadn’t considered. I’ll add a feature to allow custom URLs for other non-Ollama providers as well—or feel free to submit a PR to add it.

**Comment by avi7611** [comment]
can you tell/redirect me to the code where you defining the API URL links for various providers ?

**Comment by 0x4D31** [comment]
https://github.com/0x4D31/galah/commit/04dc8a981c8681e6b97c642db38f57fe316996ed
