### ISSUE TITLE
Not able to change API-Key via Docker

### ISSUE THREAD

**Issue by SimonKling** [0x4D31/galah#6]
When I try to set my api key with this command 

docker run -d -p 8080:8080 -p 8443:8443 -p 443:443 -p 8080:8080 -e LLM_API_KEY='my-Key' infosecb/galah:latest

I encounter this problem 
Error generating OpenAI response: error, status code: 401, message: Incorrect API key provided: ks-7xvA2*******MPLE.

I know for a fact that is not my API-Key shown there because it does not start with ks.

**Comment by 0x4D31** [comment]
Ah yes, because I recently pushed an update to the repo, but haven't updated the Docker image yet. Use API_KEY (instead of LLM_API_KEY) if you want to use the infosecb/galah image (old version), or build a new Docker image.

**Comment by 0x4D31** [comment]
Updated the README.
